### ISSUE TITLE
settings.cfg errors

### ISSUE THREAD

**Issue by veritas-krash** [AllTheMods/Server-Scripts#1]
The new settings.cfg is not set up right. The ";" at the end of each line is not needed - in fact it is causing the script to not find the URL:

DEBUG: Starting install of Forge/Minecraft server binaries
DEBUG: (wget) Downloading DISABLE;
converted 'http://DISABLE;' (ANSI_X3.4-1968) -> 'http://DISABLE;' (UTF-8)
--2017-05-15 19:41:54--  http://disable;/
Resolving disable; (disable;)... failed: Name or service not known.
wget: unable to resolve host address 'disable;'

**Comment by veritas-krash** [comment]
FORGE_JAR is missing too.
`;Details/Help Found here: https://github.com/AllTheMods/Server-Scripts
MAX_RAM=6G
JAVA_ARGS=-server -d64 -Xms2G -XX:+ExplicitGCInvokesConcurrent -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseConcMarkSweepGC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:UseSSE=3
CRASH_COUNT=10
CRASH_TIMER=600
RUN_FROM_BAD_FOLDER=0
IGNORE_OFFLINE=0
IGNORE_JAVA_CHECK=0
USE_SPONGE=0
FORGE_JAR=forge.jar
MODPACK_NAME=All The Mods 1
MCVER=1.10.2
FORGEVER=12.18.3.2297
FORGEURL=DISABLE`

**Comment by Dijkstra1** [comment]
Fixed in 71a4e52ee32942a45d7ba04be1b611f58acfca00
