### ISSUE TITLE
ServerStart.bat installing forge over and over again

### ISSUE THREAD

**Issue by LukeSkywalk3r** [AllTheMods/Server-Scripts#13]
I've used a fresh install of v4.1 and when i run the script, it either can't find forge or doesn't install it correctly in the first place. When I start it, and let it do it's thing, I repeatedly get this cmd output:

```
*** Loading All The Mods 3 Server ***
Running Forge 2497 for Minecraft 1.12.2

::::::::::::::::::::::::::::::::::::::::::::::::::::
   Minecraft-Forge Server install/launcher script
   (Created by the "All The Mods" modpack team)
::::::::::::::::::::::::::::::::::::::::::::::::::::

This script will launch a Minecraft Forge Modded server

FOR HELP (or more details);
   Github:   https://github.com/AllTheMods/Server-Scripts
   Discord:  https://discord.gg/FdFDVWb


INFO: Checking java installation...
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
Checking if current folder is valid...
Checking for basic internet connectivity...
Checking for forge/minecraft binaries...
FORGE 14.23.0.2497 binary not found, re-installing...
Clearing old files before installing forge/minecraft...


Existing forge installer already found...
Default is to use this installer and not re-download

Installing Forge now, please wait...
```

It then says that it has forge installed and starts over...and doesn't find forge installed, so it re-installs it....

**Comment by OrdinatorStouff** [comment]
If you look in the directory while the bat is running, do you see it downloading files? Do you see a forge-installer or a forge-universal in there at any point?

**Comment by LukeSkywalk3r** [comment]
I tried it today as-is (or as i left it rather) and it worked. I can see however that it downloaded forge-1.12.2-14.23.0.2497-installer.jar back then. Today it downloaded forge-1.12.2-14.23.0.2497-universal.jar and like I said, it works now...

**Comment by connorb777** [comment]
I'm getting the same issue, mine is still downloading the installer version and not the universal version even though the link in the settings.cfg says universal at the end...
