### ISSUE TITLE
Java 9

### ISSUE THREAD

**Issue by Forgrim** [AllTheMods/Server-Scripts#15]
I have installed Java 9 and the script does not find it.

![Image of Error](https://puu.sh/xWlAU/12362d73f4.PNG)

[serverstart.log](https://github.com/AllTheMods/Server-Scripts/files/1379651/serverstart.log)

**Comment by OrdinatorStouff** [comment]
looks like the output of the java version message isn't the same. 
Still, at this time JAVA 9 is pretty far off from being usable in modded MC so I think I'll remove the supposed validation for JAVA 9 in the first place.
