### ISSUE TITLE
crashing server on start up.

### ISSUE THREAD

**Issue by JamRobLam** [AllTheMods/Server-Scripts#17]
[crash-2017-10-19_13.19.05-server.txt](https://github.com/AllTheMods/Server-Scripts/files/1399383/crash-2017-10-19_13.19.05-server.txt)

**Comment by OrdinatorStouff** [comment]
I have no idea how I missed seeing this for so long O_O this wouldn't have been the correct repo to post that issue either (which looks like duplicate mods in mod folder like when you copy new serverfiles over old serverfiles without clearing directories first)

**Comment by JamRobLam** [comment]
Thank you for getting back to me regardless, next chance I get ill check it. If I can. :D
