### ISSUE TITLE
NoInternetConnectivityMinecraftForgeNet

### ISSUE THREAD

**Issue by WagnerBenjamin** [AllTheMods/Server-Scripts#2]
Hi, 
this is the 1st time i launch your modpack and i'm getting the error in the title.
I tried disabling firewall, did not work.
I tried to ping minecraftforge.net, it worked but the launcher still won't start.

Thanks

Here are the logs

 ----------------------------------------------------------------- 
INFO: Starting batch at 5/01: 91539 
----------------------------------------------------------------- 
 
DEBUG: Current Dir is C:\AllTheModsServer -- trying to change to C:\AllTheModsServer\ 
INFO: Checking that settings.cfg exists 
DEBUG: settings.cfg Found. Logging full contents below: 
;Details/Help Found here: https://github.com/AllTheMods/Server-Scripts

MAX_RAM=5G; 
JAVA_ARGS=-server -d64 -Xms1G -XX:+ExplicitGCInvokesConcurrent -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseConcMarkSweepGC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:UseSSE=3;
CRASH_COUNT=10; 
CRASH_TIMER=600; 
RUN_FROM_BAD_FOLDER=0; 
IGNORE_OFFLINE=0; 
IGNORE_JAVA_CHECK=0; 
USE_SPONGE=0;

MODPACK_NAME=All The Mods 1;
MCVER=1.10.2
FORGEVER=12.18.3.2297; 
FORGEURL=DISABLE; 
 
INFO: Loading variables from settings.cfg 
DEBUG: Starting variable definitions: 
DEBUG: MC_SERVER_MAX_RAM=5G 
DEBUG: MC_SERVER_FORGE_JAR= 
DEBUG: MC_SERVER_SPONGE_BOOT= 
DEBUG: MC_SERVER_JVM_ARGS=-Xmx5G -server -d64 -Xms1G -XX:+ExplicitGCInvokesConcurrent -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseConcMarkSweepGC -Dsun.rmi.dgc.server.gcInterval 
DEBUG: MC_SERVER_MAX_CRASH=10 
DEBUG: MC_SERVER_CRASH_TIMER=600 
DEBUG: MC_SERVER_IGNORE_OFFLINE=0 
DEBUG: MC_SERVER_RUN_FROM_BAD_FOLDER=0 
DEBUG: MC_SERVER_MCVER=1.10.2 
DEBUG: MC_SERVER_FORGEVER=12.18.3.2297 
DEBUG: MC_SERVER_FORGESHORT=2297 
DEBUG: MC_SERVER_FORGEURL=DISABLE 
DEBUG: MC_SERVER_SPONGE=0 
DEBUG: MC_SERVER_PACKNAME=All The Mods 1 
DEBUG: MC_SERVER_SPONGEURL= 
DEBUG: MC_SERVER_SPONGEBOOTSTRAPURL= 
DEBUG: MC_SERVER_ERROR_REASON=Unspecified 
DEBUG: MC_SERVER_TMP_FLAG=0 
DEBUG: MC_SERVER_CRASH_COUNTER=1 
DEBUG: MC_SERVER_CRASH_YYYYMMDD=5/01 
DEBUG: MC_SERVER_CRASH_HHMMSS= 91539 
DEBUG: Current directory file listing: 
 Le volume dans le lecteur C n'a pas de nom.
 Le num‚ro de s‚rie du volume est 3E80-BDCC

 R‚pertoire de C:\AllTheModsServer

26/05/2017  09:15    <DIR>          .
26/05/2017  09:15    <DIR>          ..
26/05/2017  09:11    <DIR>          config
26/05/2017  09:14    <DIR>          mods
26/05/2017  09:14    <DIR>          resources
26/05/2017  09:14    <DIR>          scripts
09/05/2017  20:26            39ÿ725 ServerStart.bat
26/05/2017  09:15             1ÿ939 serverstart.log
19/05/2017  08:44            10ÿ045 ServerStart.sh
19/05/2017  08:44               536 settings.cfg
               4 fichier(s)           52ÿ245 octets
               6 R‚p(s)  99ÿ837ÿ104ÿ128 octets libres
DEBUG: JAVA version output (java -d64 -version): 
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
INFO: Found 64-bit Java 1.8 
...64-bit Java 1.8 found! 
INFO: Checking if current folder is valid... 
INFO: Checking for basic internet connectivity... 
WARN: Ping of "8.8.8.8" Failed 
INFO: Checking for forge/minecraft binaries... 
INFO: FORGE 12.18.3.2297 not found, re-installing... 
INFO: Clearing and installing forge/minecraft... 

BITSADMIN version 3.0
BITS administration utility.
(C) Copyright 2000-2006 Microsoft Corp.

BITSAdmin is deprecated and is not guaranteed to be available in future versions of Windows.
Administrative tools for the BITS service are now provided by BITS PowerShell cmdlets.

0 out of 0 jobs canceled.
Fichier introuvable
 DEBUG: MC_SERVER_TMP_FLAG=1 
Fichier introuvable - 1
Impossible de trouver C:\AllTheModsServer\*forge*installer*.jar*
Fichier introuvable - 1
ERROR: Could not reach minecraftforge.net 
ERROR: Error flagged, reason is: "NoInternetConnectivityMinecraftForgeNet" 
WARN: Server startup script is exiting. Dumping current vars: 
DEBUG: MC_SERVER_MAX_RAM=5G 
DEBUG: MC_SERVER_FORGE_JAR= 
DEBUG: MC_SERVER_SPONGE_BOOT= 
DEBUG: MC_SERVER_JVM_ARGS=-Xmx5G -server -d64 -Xms1G -XX:+ExplicitGCInvokesConcurrent -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseConcMarkSweepGC -Dsun.rmi.dgc.server.gcInterval 
DEBUG: MC_SERVER_MAX_CRASH=10 
DEBUG: MC_SERVER_CRASH_TIMER=600 
DEBUG: MC_SERVER_IGNORE_OFFLINE=0 
DEBUG: MC_SERVER_RUN_FROM_BAD_FOLDER=0 
DEBUG: MC_SERVER_MCVER=1.10.2 
DEBUG: MC_SERVER_FORGEVER=12.18.3.2297 
DEBUG: MC_SERVER_FORGESHORT=2297 
DEBUG: MC_SERVER_FORGEURL=DISABLE 
DEBUG: MC_SERVER_SPONGE=0 
DEBUG: MC_SERVER_PACKNAME=All The Mods 1 
DEBUG: MC_SERVER_SPONGEURL= 
DEBUG: MC_SERVER_SPONGEBOOTSTRAPURL= 
DEBUG: MC_SERVER_ERROR_REASON=NoInternetConnectivityMinecraftForgeNet 
DEBUG: MC_SERVER_TMP_FLAG=  
DEBUG: MC_SERVER_CRASH_COUNTER=1 
DEBUG: MC_SERVER_CRASH_YYYYMMDD=5/01 
DEBUG: MC_SERVER_CRASH_HHMMSS= 91539 
DEBUG: Current directory file listing: 
 Le volume dans le lecteur C n'a pas de nom.
 Le num‚ro de s‚rie du volume est 3E80-BDCC

 R‚pertoire de C:\AllTheModsServer

26/05/2017  09:15    <DIR>          .
26/05/2017  09:15    <DIR>          ..
26/05/2017  09:11    <DIR>          config
26/05/2017  09:14    <DIR>          mods
26/05/2017  09:14    <DIR>          resources
26/05/2017  09:14    <DIR>          scripts
09/05/2017  20:26            39ÿ725 ServerStart.bat
26/05/2017  09:15             4ÿ752 serverstart.log
19/05/2017  08:44            10ÿ045 ServerStart.sh
19/05/2017  08:44               536 settings.cfg
               4 fichier(s)           55ÿ058 octets
               6 R‚p(s)  99ÿ837ÿ067ÿ264 octets libres
DEBUG: JAVA version output (java -d64 -version): 
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

BITSADMIN version 3.0
BITS administration utility.
(C) Copyright 2000-2006 Microsoft Corp.

BITSAdmin is deprecated and is not guaranteed to be available in future versions of Windows.
Administrative tools for the BITS service are now provided by BITS PowerShell cmdlets.

0 out of 0 jobs canceled.

**Comment by ShiiFu** [comment]
Hi,

I think this error is fixed by the commit 1486c73
I had got the same and I used the last version of the ServerStart.bat on dev branch, it works for me.

Regards,
ShiiFu

**Comment by Dijkstra1** [comment]
Fixed in lasted commint
