### ISSUE TITLE
 Could not create the Java Virtual Machine. -d64 unrecognised command.

### ISSUE THREAD

**Issue by ManudaNZ** [AllTheMods/Server-Scripts#23]
I installed Jdk 8 and jdk 10.1 but I still get this. Do I have to put something in my PATH: variables to get this to work?

**Comment by Blueletric** [comment]
JDK 10.1 does not work with any current Minecraft version, delete it and the server should start normally

**Comment by Boomflex** [comment]
Java 10 not supported.

**Comment by ManudaNZ** [comment]
Yes!!! Uninstalled 10.1 java and jdk10.1, now it all works fine. thanks
