### ISSUE TITLE
No means yes

### ISSUE THREAD

**Issue by Ricket** [AllTheMods/Server-Scripts#3]
After doing `/stop`:

```
> Server will restart in ~10 seconds. No input needed...
Restart now (y) or exit to shell (n)?  n
Ping to Google DNS successfull
Ping to L4 successfull
Rebooting now!


Starting server
```

I typed "n" to exit to shell, but instead it did a restart.

I can see in [ServerStart.sh](https://github.com/AllTheMods/Server-Scripts/blob/master/ServerStart.sh#L279) that it is in fact looking for "y" or "yes" to indicate exit to shell, which is the opposite of the message. One of these should be flipped.

**Comment by Dijkstra1** [comment]
Already fixed in the dev branch guess there no reason not to merge it now just need to check a few things with @OrdinatorStouff
