### ISSUE TITLE
Error: Could not find valid java version installed

### ISSUE THREAD

**Issue by choco-green** [AllTheMods/Server-Scripts#38]
help *facepalm*
![image](https://user-images.githubusercontent.com/33989421/47604258-e9a2bb00-d9ee-11e8-9336-6bbc1ce1b919.png)

[ServerStart.log](https://hastebin.com/ijeruyepez.hs)

**Comment by DKnightADRI** [comment]
ERROR: Could not find 64-bit Java 1.8 installed or in PATH

It means you don't have java 64-bit installed or haven't set the PATH (windows environment variable) to it.

**Comment by Yoosk** [comment]
I'd suggest to install [this java(Windows Offline (64-bit)](https://java.com/en/download/manual.jsp#win) and remove any other version. 
It seems that you either have different one like java 9 or 10, or 32 bit, which is not supported.

**Comment by choco-green** [comment]
thx a lot guys :D :+1:

**Comment by pafff161** [comment]
> ERROR: Could not find 64-bit Java 1.8 installed or in PATH
> 
> It means you don't have java 64-bit installed or haven't set the PATH (windows environment variable) to it.

ik this is old but were can i set the path?

**Comment by choco-green** [comment]
Im assuming your playing minecraft on windows, 
Search "edit the system environment variables" on windows, 
Click on "environment variables" on the bottom right (in "Advanced" tab)
Within system variables list, select one with "Path" and add the relevant path with "New"

Hope this answers your question :>

**Comment by pafff161** [comment]
OK  so I need more help. I got as far as finding the "Path" in the system variables list, but  i don't understand what's the next step. What should I type in when I click the "New" box ?

**Comment by choco-green** [comment]
what pack are you playing? Please install the relevant java installation based on [official wiki](https://minecraft.fandom.com/wiki/Tutorials/Update_Java) including where to download etc.

**Comment by pafff161** [comment]
Im playing Forever Stranded(https://www.curseforge.com/minecraft/modpacks/forever-stranded) 1.10.2. I just installed the latest Java from https://www.java.com/en/download/manual.jsp as the batch file said.  which is jre1.8.0_341

**Comment by choco-green** [comment]
put the path of installation of Java in the system path envionment variable

it should love something like this C:\Program Files\Java\jdk1.8.0_341, or wherever you have installed 

:>

**Comment by pafff161** [comment]
I did that and it still says Could not find valid java version installed . I think I will just giveup. Thanks for trying to help me.

**Comment by pafff161** [comment]
Nvm I had to set the bin folder of java in the path eviriment varriable. but i have another problem **** ERROR ****
There was an Error, Code: "NoInternetConnectivityMinecraftForgeNet"
