### ISSUE TITLE
Carriage returns in settings.cfg when downloading repo as zip file

### ISSUE THREAD

**Issue by gdcooman** [AllTheMods/Server-Scripts#46]
I downloaded the repo as a zip file and upon running the script it kept giving me erros. So I looked at the serverstart.log and noticed these carriage returns. Since I am on ubuntu it didn't like these because the script couldn't find the files it needed. (the variables didn't match the actual file names). 
I removed the carriage returns from the settings.cfg file and this time the script worked perfectly.

So I would suggest handling this in the bash script.

Anyways, thanks for the great script! 😄

**Comment by zeue** [comment]
anyone who stumbles on this, just use something like `dos2unix` on the file
