### ISSUE TITLE
can't start a server

### ISSUE THREAD

**Issue by kbdavies** [AllTheMods/Server-Scripts#52]
i am on a linux ubuntu and i have fallowed the readme and installed java but it wont work can you help plase

<pre>sh ServerStart.sh
openjdk version &quot;11.0.3&quot; 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

About to start server. Force re-install (y/n)?  y
User chose to manually re-install server files
Starting install of Forge/Minecraft server binaries
http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2825/forge-1.12.2-14.23.5.2825-installer.jar
Moving unneeded files/folders to ./DELETEME
Installing Forge Server, please wait...
Deleting Forge installer (no longer needed)
Ping to Google DNS successfull
Ping to L4 successfull

Starting server
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Server will restart in ~10 seconds. No input needed...
Restart now (y) or exit to shell (n)?  Ping to Google DNS successfull
Ping to L4 successfull
Rebooting now!

Starting server
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Server will restart in ~10 seconds. No input needed...
Restart now (y) or exit to shell (n)?  Ping to Google DNS successfull
Ping to L4 successfull
Rebooting now!

Starting server
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Server will restart in ~10 seconds. No input needed...
Restart now (y) or exit to shell (n)?  Ping to Google DNS successfull
Ping to L4 successfull
Rebooting now!

Starting server
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Server will restart in ~10 seconds. No input needed...
Restart now (y) or exit to shell (n)?  Ping to Google DNS successfull
Ping to L4 successfull
Rebooting now!

Starting server
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
The server has crashed to many times
</pre>

**Comment by Lartza** [comment]
You need openjdk-8-jre-headless. You can install that using APT and remove openjdk-11-jre/openjdk-11-jre-headless or set 8 as default using `sudo update-alternatives --config java`

**Comment by kbdavies** [comment]
Thank you all working now
