### ISSUE TITLE
Unable to run server commands when launched through ServerStart.sh

### ISSUE THREAD

**Issue by jtc42** [AllTheMods/Server-Scripts#54]
When my server is launched through ServerStart.sh, I'm unable to run server commands from the console. The input just gets written to the shell, but nothing ever gets executed.

Is this something janky with my setup? I was wondering if it's perhaps related to the Java file being launcher from within a while loop.

Any thoughts would be great.

**Comment by Yoosk** [comment]
I happened to me as well, on first launch, had to entirely close to script and launch it again. Then it looks as expected.

**Comment by jtc42** [comment]
Thanks. It seems to be temperamental, so I've just shifted to using RCON for managing the server. Will close as it seems like a non-issue now.
