### ISSUE TITLE
ServerStart.bat installing forge over and over again

### ISSUE THREAD

**Issue by SynAmardo** [AllTheMods/Server-Scripts#57]
I´ve installed the Modpack Forever Stranded and everything worked well till I started this ServerStart.bat file, it installed the forge-1.10.2-12.18.3.2511-installer and the forge-1.10.2-12.18.3.2185-universal file. I started both of them and started the ServerStart.bat file again but it keeps saying

```
*** Loading Forever Stranded Server ***
Running Forge 2511 for Minecraft 1.10.2

::::::::::::::::::::::::::::::::::::::::::::::::::::
   Minecraft-Forge Server install/launcher script
   (Created by the "All The Mods" modpack team)
::::::::::::::::::::::::::::::::::::::::::::::::::::

This script will launch a Minecraft Forge Modded server

FOR HELP (or more details);
   Github:   https://github.com/AllTheMods/Server-Scripts
   Discord:  https://discord.gg/FdFDVWb


INFO: Checking java installation...
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
Checking if current folder is valid...
Checking for basic internet connectivity...
Checking for forge/minecraft binaries...
FORGE 12.18.3.2511 binary not found, re-installing...
Clearing old files before installing forge/minecraft...


Existing forge installer already found...
Default is to use this installer and not re-download

Installing Forge now, please wait...
```

after this it tells me that forge and minecraft is intalled and start the same thing again, I honestly tried everything and now I need help... Did I missed something, did I specify the wrong website in FORGEURL in the settings.cfg file? Im adding two pictures, one of the console and one of my folder.

![Konsole](https://user-images.githubusercontent.com/55048325/64486614-73d2c700-d22f-11e9-8220-c9a319550700.PNG)

![Folder](https://user-images.githubusercontent.com/55048325/64486625-a2e93880-d22f-11e9-8b7b-87fe0e210a69.PNG)

**Comment by Darkere** [comment]
Change a line in the settings.cfg file from
FORGEURL= DISABLE;
to
FORGEURL=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2511/forge-1.10.2-12.18.3.2511-installer.jar;

**Comment by SynAmardo** [comment]
thx for the fast answer

I did it, dont know if its stuck now on downloading forge but Im waiting

**Comment by SynAmardo** [comment]
> Change a line in the settings.cfg file from
> FORGEURL= DISABLE;
> to
> FORGEURL=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2511/forge-1.10.2-12.18.3.2511-installer.jar;

**Comment by SynAmardo** [comment]
shit, didnt want to close this xD
