### ISSUE TITLE
ServerStart.sh: 36: ServerStart.sh: Syntax error: "(" unexpected (expecting "then")

### ISSUE THREAD

**Issue by Minemobs** [AllTheMods/Server-Scripts#60]
hello
why when i launch my server he crash and say
ServerStart.sh: 36: ServerStart.sh: Syntax error: "(" unexpected (expecting "then")
bash: erreur de syntaxe près du symbole inattendu « ( »

**Comment by excodex** [comment]
start like this:
`./ServerStart.sh`
not like this:
`sh ServerStart.sh`
