### ISSUE TITLE
Server keeps trying to install forge without progress

### ISSUE THREAD

**Issue by adam-achorn** [AllTheMods/Server-Scripts#67]
I changed the version of forge to 14.23.5.2854 in the settings and now it keeps installing that over and over without progressing. I've seen others report this issue but trying what they did to solve it didn't work.

**Comment by darrenswhite** [comment]
@DJSlimJim using 14.23.5.2847 worked for me. 2852 and 2854 both wouldn't work.

**Comment by adam-achorn** [comment]
Awesome. Works, thanks!
