### ISSUE TITLE
Unable to start the Server

### ISSUE THREAD

**Issue by ghost** [AllTheMods/Server-Scripts#76]
Hello,
Everytime I start the "ServerStart.bat", the Command Panel turns yellow and it closes immediately.
Please help me with the error

This the the Debug.log
[debug.log](https://github.com/AllTheMods/Server-Scripts/files/5432701/debug.log)

**Comment by whatthedrunk** [comment]
Volcano Block v1.0.39? Not an ATM pack but you should be asking here now. https://github.com/BloodyMods/ServerStarter/issues

**Comment by ghost** [comment]
OK thank you very much :) 
I´ll ask there
