### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by ghost** [AllTheMods/Server-Scripts#77]
Hi I try to start server but when I do it comes up with this
![image](https://user-images.githubusercontent.com/73684057/97664055-b7634280-1a7a-11eb-95a5-9cdf9bc09788.png)
And when I try to bypass java check this happens

![image](https://user-images.githubusercontent.com/73684057/97664490-d3ff7a80-1a7a-11eb-89c3-18c02ddc6ec9.png)
This pack is using your startbat file so I was hoping you could help me

**Comment by sudotask** [comment]
i have the same exact issue

**Comment by radiomike** [comment]
You need to install a 64bit java 8 or java 11. Java 11 is recommended for this pack.

**Comment by starforcraft** [comment]
> You need to install a 64bit java 8 or java 11. Java 11 is recommended for this pack.

He plays on 1.12.2 so he needs Java 8. Java 11 wouldn't work.

**Comment by sudotask** [comment]
![image](https://user-images.githubusercontent.com/86846218/124321803-f9eb9a80-db86-11eb-9d66-bce4bb2055ae.png)

i have installed all of them but still have the same issue and i assume having multiple versions of java isn't particularly bad?
